language: node_js
node_js:
  - "12.13.1"
dist: trusty
sudo: required
branches:
  only:
  - main
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist/travis-demo
#   on:
#     branch: master