language: node_js
node_js:
  - "12.13.1"
dist: trusty
sudo: required
branches:
  only:
  - main
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  # - npm run test-headless
  - ng build --prod

before_deploy:
  - cd dist
  - cd test-app

deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-southeast-1
  app: test-app
  env: TestApp-env1
  bucket_name:  test-app-mckinley
  # skip_cleanup: true
  on:
    branch: main